# This is a basic workflow to help you get started with Actions

name: Keras_bazel_build_and_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ regnet ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build: 
    
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: regnet
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

      - name: Create environment
        run: |
          mkdir keras_env
          python3 -m venv keras_env
          source keras_env/bin/activate
      
      - name: Install Bazel
        uses: abhinavsingh/setup-bazel@v3
        
      - name: Build
        run: |
          bazel build //keras/tools/pip_package:build_pip_package
          $GITHUB_WORKSPACE/keras/bazel-bin/keras/tools/pip_package/build_pip_package $GITHUB_WORKSPACE/keras_pkg
          pip install -r $GITHUB_WORKSPACE/keras/requirements.txt
          pip uninstall -y keras-nightly
          pip install --upgrade tf-nightly
          pip install $GITHUB_WORKSPACE/keras_pkg/keras-2.7.0-py2.py3-none-any.whl
          
      
      - name: Test
        run: |
          bazel test keras/applications/applications_test
